// @zsm/design 零依赖生成器：读 src/tokens.data.mjs →
//   dist/tokens.wxss（page 级 CSS 变量，px×2→rpx，颜色原样）
//   dist/theme.ts  （RN 用 px 数值 + re-export motion）
// 产物落盘提交入库；`make design-build` 用 git diff 校验无漂移。
// 幂等：相同输入字节级相同输出（颜色字符串原样，不做大小写/压缩归一）。
import { mkdir, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { colors, radius, space, sizes, type, shadows } from '../src/tokens.data.mjs'

const rootDir = dirname(dirname(fileURLToPath(import.meta.url)))
const distDir = join(rootDir, 'dist')

const rpx = (px) => `${px * 2}rpx`
const header = (target) => [
  `/* AUTO-GENERATED by scripts/generate.mjs — DO NOT EDIT.`,
  ` * 单一事实来源：src/tokens.data.mjs（权威表 §4.2）`,
  ` * 重新生成：pnpm --filter @zsm/design build`,
  ` * 目标：${target} */`,
  ''
].join('\n')

function buildWxss() {
  const lines = []
  lines.push('page {')
  for (const [key, value] of Object.entries(colors)) {
    const cssName = key.replace(/([A-Z])/g, '-$1').toLowerCase()
    lines.push(`  --${cssName}: ${value};`)
  }
  for (const [key, value] of Object.entries(radius)) {
    lines.push(`  --radius-${key}: ${key === 'pill' ? '999rpx' : rpx(value)};`)
  }
  for (const [key, value] of Object.entries(space)) {
    lines.push(`  --space-${key}: ${rpx(value)};`)
  }
  for (const [key, value] of Object.entries(sizes)) {
    const cssName = key.replace(/([A-Z])/g, '-$1').toLowerCase()
    lines.push(`  --${cssName}: ${rpx(value)};`)
  }
  for (const [key, shadow] of Object.entries(shadows)) {
    const cssName = key.replace(/([A-Z])/g, '-$1').toLowerCase()
    lines.push(`  --shadow-${cssName}: 0 ${rpx(shadow.y)} ${rpx(shadow.blur)} ${shadow.color};`)
  }
  lines.push('}')
  return header('小程序 app.wxss @import（designWidth 750，px×2→rpx）') + lines.join('\n') + '\n'
}

function buildThemeTs() {
  // 值只可能是 string | number | {y,blur,color}；键全部是合法标识符，裸键输出
  const emit = (value, indent) => {
    if (value && typeof value === 'object') {
      const body = Object.entries(value)
        .map(([k, v]) => `${indent}  ${k}: ${emit(v, `${indent}  `)}`)
        .join(',\n')
      return `{\n${body}\n${indent}}`
    }
    return JSON.stringify(value)
  }
  const obj = (source, indent) => emit(Object.fromEntries(Object.entries(source)), indent)
  const lines = []
  lines.push('export const theme = {')
  lines.push(`  color: ${obj(colors, '  ')},`)
  lines.push(`  radius: ${obj(radius, '  ')},`)
  lines.push(`  space: ${obj(space, '  ')},`)
  lines.push(`  size: ${obj(sizes, '  ')},`)
  lines.push(`  type: ${obj(type, '  ')},`)
  lines.push(`  shadow: ${obj(shadows, '  ')}`)
  lines.push('} as const')
  lines.push('')
  lines.push('export type Theme = typeof theme')
  return (
    header('RN / 手机端 theme（px 数值，与 tokens.wxss 同源）') +
    lines.join('\n') +
    '\n\nexport * from "../src/motion"\n'
  )
}

await mkdir(distDir, { recursive: true })
await writeFile(join(distDir, 'tokens.wxss'), buildWxss(), 'utf8')
// scss 局部副本：内容与 tokens.wxss 完全一致。Taro/Vite 的 scss 管线无法
// 从 node_modules 解析 .wxss 后缀（nativeStyleImporter 只做相对路径），
// 小程序 app.scss 走标准 scss 包解析 import 本文件。
await writeFile(join(distDir, 'tokens.scss'), buildWxss(), 'utf8')
await writeFile(join(distDir, 'theme.ts'), buildThemeTs(), 'utf8')
console.log('[design] generated dist/tokens.wxss + dist/tokens.scss + dist/theme.ts')
